### PR TITLE
Fixes #4

### LINKED ISSUE #4: this.pass when !token
Thank you for your work on this library, @vinialbano!

Should [this](https://github.com/vinialbano/passport-magic-link/blob/master/src/Strategy.js#L138) be set to `this.fail`?

### PR DESCRIPTION
**Pull request by phof**
@vinialbano Here's a PR to close #4

### CODE REVIEW

**Comment by phof** [comment]
@vinialbano Thoughts on this?

**Comment by vinialbano** [comment]
Thanks, @phof! And sorry for the delay

**Comment by phof** [comment]
Thank you, @vinialbano! Can you push the changes to npm?

**Comment by vinialbano** [comment]
@phof published!

**Pull request merged**
